### ISSUE TITLE
Update asset-lib entry to latest version

### ISSUE THREAD

**Issue by nobuyukinyuu** [JeromeOrtali/TileSetCutter#3]
Hi!  Thank you for accepting my pull request.  To finalize the changes, you'll probably want to submit an edit to the asset-library so that users will be able to install the new version from within the Godot editor.  It's as simple as changing the commit hash to the latest version.

Thanks again, I learned a lot about how to write plugins from working with your addon.

**Comment by JeromeOrtali** [comment]
Hi, the changes are pending on the asset library. thanks for your participation.
